### ISSUE TITLE
The game fails to pass the Acid2Test

### ISSUE THREAD

**Issue by sdsnatcher** [santiontanon/talesofpopolon#2]
The game fails to pass the Acid2Test

There are some very few placed you coded the VDP access more or less like this:

```
ld c,0x98
{some code}
out (c),a

```
You just have to replace it with:

```
ld bc,(VDP.DW)
{some code}
out (c),a

```

You must use the ports pointed by VDP.DW or VDP.DR for writes and reads respectively.

**Comment by santiontanon** [comment]
Thanks! done with the latest commit! I have not been able to find the msxaudio.rom anywhere in the net, so I can run the Acid2Test myself though...

**Comment by santiontanon** [comment]
I'm closing this ticket, since I think it is solved now. But if it doesn't pass the test. Please do not hesitate to reopen :)
